use crate::autoinstall::{build_feature_late_commands, hash_password};
use crate::config::InjectConfig;
use crate::error::EngineResult;

/// Generate a Fedora/RHEL Kickstart configuration from InjectConfig.
///
/// The resulting `ks.cfg` content covers identity, network, packages, and a
/// `%post` section that reuses the same late-command logic as the Ubuntu
/// cloud-init path (NTP, groups, shell, sudo, services, sysctl, swap,
/// firewall, GRUB, mounts, run_commands, extra_late_commands).
pub fn generate_kickstart_cfg(cfg: &InjectConfig) -> EngineResult<String> {
    let mut lines: Vec<String> = Vec::new();

    // ── Header ───────────────────────────────────────────────────────────────
    lines.push("# Generated by ForgeISO".to_string());
    lines.push("text".to_string());

    // ── Locale / keyboard / timezone ─────────────────────────────────────────
    let locale = cfg.locale.as_deref().unwrap_or("en_US.UTF-8");
    lines.push(format!("lang {locale}"));

    let kb = cfg.keyboard_layout.as_deref().unwrap_or("us");
    lines.push(format!("keyboard {kb}"));

    let tz = cfg.timezone.as_deref().unwrap_or("UTC");
    lines.push(format!("timezone {tz} --utc"));

    // ── Root account (locked) ─────────────────────────────────────────────────
    lines.push("rootpw --lock".to_string());

    // ── User account ─────────────────────────────────────────────────────────
    if let Some(uname) = &cfg.username {
        let mut user_line = format!("user --name={uname}");
        if !cfg.user.groups.is_empty() {
            user_line.push_str(&format!(" --groups={}", cfg.user.groups.join(",")));
        }
        if let Some(pwd) = &cfg.password {
            let hashed = hash_password(pwd)?;
            user_line.push_str(&format!(" --password={hashed} --iscrypted"));
        }
        if let Some(realname) = &cfg.realname {
            user_line.push_str(&format!(" --gecos=\"{realname}\""));
        }
        lines.push(user_line);

        // SSH authorized keys (one sshkey directive per key)
        for key in &cfg.ssh.authorized_keys {
            let k = key.trim();
            if !k.is_empty() {
                lines.push(format!("sshkey --username={uname} \"{k}\""));
            }
        }
    }

    // ── Network ──────────────────────────────────────────────────────────────
    if let Some(static_ip) = &cfg.static_ip {
        // Parse CIDR notation: "10.0.0.5/24" → ip=10.0.0.5 netmask=255.255.255.0
        let (ip, mask) = parse_cidr(static_ip);
        let mut net_line =
            format!("network --bootproto=static --device=link --onboot=on --ip={ip} --netmask={mask}");
        if let Some(gw) = &cfg.gateway {
            net_line.push_str(&format!(" --gateway={gw}"));
        }
        if !cfg.network.dns_servers.is_empty() {
            net_line.push_str(&format!(
                " --nameserver={}",
                cfg.network.dns_servers.join(",")
            ));
        }
        lines.push(net_line);
    } else {
        let mut net_line =
            "network --bootproto=dhcp --device=link --onboot=on".to_string();
        if !cfg.network.dns_servers.is_empty() {
            net_line.push_str(&format!(
                " --nameserver={}",
                cfg.network.dns_servers.join(",")
            ));
        }
        lines.push(net_line);
    }

    // ── Hostname ─────────────────────────────────────────────────────────────
    if let Some(hostname) = &cfg.hostname {
        lines.push(format!("network --hostname={hostname}"));
    }

    // ── Storage layout ───────────────────────────────────────────────────────
    match cfg.storage_layout.as_deref() {
        Some("lvm") => {
            lines.push("autopart --type=lvm".to_string());
        }
        Some("zfs") => {
            // Kickstart doesn't natively support ZFS; fall back to lvm
            lines.push("autopart --type=lvm".to_string());
        }
        _ => {
            lines.push("autopart --type=plain".to_string());
        }
    }
    lines.push("clearpart --all --initlabel".to_string());

    // ── Reboot ───────────────────────────────────────────────────────────────
    lines.push("reboot".to_string());

    // ── %packages ─────────────────────────────────────────────────────────────
    lines.push(String::new());
    lines.push("%packages".to_string());
    lines.push("@^minimal-environment".to_string());
    if cfg.firewall.enabled {
        lines.push("firewalld".to_string());
    }
    for pkg in &cfg.extra_packages {
        lines.push(pkg.clone());
    }
    lines.push("%end".to_string());

    // ── %post ─────────────────────────────────────────────────────────────────
    let late_cmds = build_feature_late_commands(cfg)?;
    if !late_cmds.is_empty() {
        lines.push(String::new());
        lines.push("%post".to_string());
        // In Kickstart, the chroot is implicit for %post (runs inside installed system)
        // Strip the "chroot /target " prefix that the cloud-init helper adds
        for cmd in &late_cmds {
            let base = cmd.strip_prefix("chroot /target ").unwrap_or(cmd);
            let stripped = base.replace("/target/", "/").replace("/target ", "/ ");
            lines.push(stripped);
        }
        lines.push("%end".to_string());
    }

    Ok(lines.join("\n") + "\n")
}

/// Parse a CIDR address string (e.g. "10.0.0.5/24") into (ip, netmask).
/// Falls back to (addr, "255.255.255.0") if the prefix is missing or invalid.
fn parse_cidr(cidr: &str) -> (String, String) {
    if let Some((ip, prefix)) = cidr.split_once('/') {
        let mask = prefix_to_mask(prefix.parse::<u8>().unwrap_or(24));
        (ip.to_string(), mask)
    } else {
        (cidr.to_string(), "255.255.255.0".to_string())
    }
}

fn prefix_to_mask(prefix: u8) -> String {
    let bits = if prefix >= 32 {
        0xFFFF_FFFFu32
    } else {
        !(0xFFFF_FFFFu32 >> prefix)
    };
    format!(
        "{}.{}.{}.{}",
        (bits >> 24) & 0xFF,
        (bits >> 16) & 0xFF,
        (bits >> 8) & 0xFF,
        bits & 0xFF
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{InjectConfig, IsoSource};

    fn base_cfg() -> InjectConfig {
        InjectConfig {
            source: IsoSource::from_raw("/tmp/fedora.iso"),
            out_name: "out.iso".to_string(),
            ..Default::default()
        }
    }

    #[test]
    fn test_kickstart_minimal() {
        let cfg = base_cfg();
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(ks.contains("# Generated by ForgeISO"));
        assert!(ks.contains("rootpw --lock"));
        assert!(ks.contains("reboot"));
        assert!(ks.contains("%packages"));
        assert!(ks.contains("%end"));
    }

    #[test]
    fn test_kickstart_with_user() {
        let mut cfg = base_cfg();
        cfg.username = Some("admin".to_string());
        cfg.password = Some("secret".to_string());
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(ks.contains("user --name=admin"));
        assert!(ks.contains("--iscrypted"));
    }

    #[test]
    fn test_kickstart_with_static_ip() {
        let mut cfg = base_cfg();
        cfg.static_ip = Some("10.0.0.5/24".to_string());
        cfg.gateway = Some("10.0.0.1".to_string());
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(ks.contains("--bootproto=static"));
        assert!(ks.contains("--ip=10.0.0.5"));
        assert!(ks.contains("--netmask=255.255.255.0"));
        assert!(ks.contains("--gateway=10.0.0.1"));
    }

    #[test]
    fn test_kickstart_packages() {
        let mut cfg = base_cfg();
        cfg.extra_packages = vec!["curl".to_string(), "git".to_string()];
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(ks.contains("curl"));
        assert!(ks.contains("git"));
    }

    #[test]
    fn test_cidr_parsing() {
        assert_eq!(
            parse_cidr("192.168.1.10/24"),
            ("192.168.1.10".to_string(), "255.255.255.0".to_string())
        );
        assert_eq!(
            parse_cidr("10.0.0.1/16"),
            ("10.0.0.1".to_string(), "255.255.0.0".to_string())
        );
    }
}
